### ISSUE TITLE
super little building bug

### ISSUE THREAD

**Issue by neskov7** [WEEE-Open/WEEEbsite#1]
add an empty output folder in the repo to not waste time on stupid errors while building

**Comment by lvps** [comment]
Git does not support [adding empty directories to repositories](https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F), even though some hacks allow that (= placing a gitignore file inside the directory). I've updated Mecahtronic Anvil instead, so it creates the output directory on first run.
